export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

export const ADD_PRODUCT_DETAILS = "ADD_PRODUCT_DETAILS";
export const ADD_BOOKED_DETAILS = "ADD_BOOKED_DETAILS";

export const ADD_USER_DATA = "ADD_USER_DATA";
